env:
  global:
  	- LD_LIBRARY_PATH=/usr/local/lib
install:
  - curl http://www.rust-lang.org/rustup.sh | sudo sh -
  - wget http://www.fmod.org/download/fmodex/api/Linux/fmodapi44439linux.tar.gz
  - tar xvf fmodapi44439linux.tar.gz
  - sudo cp -r fmodapi44439linux/api/lib/* /usr/local/lib/.
script:
  - rustc --version
  - cargo build