language: rust
rust:
- stable
sudo: true
env:
  global:
    - LD_LIBRARY_PATH=/usr/local/lib
install:
  - wget http://www.guillaume-gomez.fr/fmodapi44439linux.tar.gz
  - tar xvf fmodapi44439linux.tar.gz
  - sudo cp -r fmodapi44439linux/api/lib/* /usr/local/lib/.
  - mkdir sfml_install
  - wget http://www.sfml-dev.org/files/SFML-2.4.2-sources.zip --no-check-certificate
  - unzip -q SFML-2.4.2-sources.zip
  - cd SFML-2.4.2 && mkdir build && cd build && cmake .. && make && sudo cp -r lib/* /usr/local/lib/.
  - make DESTDIR=/home/travis/build/GuillaumeGomez/rust-music-player/sfml_install install
  - cd ../..
  - wget http://www.sfml-dev.org/files/CSFML-2.4-sources.zip --no-check-certificate
  - unzip -q CSFML-2.4-sources.zip
  - cd CSFML-2.4
  - mkdir cmake/Modules
  - cp ../SFML-2.4.2/cmake/Modules/FindSFML.cmake cmake/Modules
  - mkdir build && cd build && cmake -DCMAKE_MODULE_PATH=/home/travis/build/GuillaumeGomez/rust-music-player/CSFML-2.4/cmake/Modules -DSFML_ROOT=/home/travis/build/GuillaumeGomez/rust-music-player/sfml_install/usr/local .. && make && sudo cp -r lib/* /usr/local/lib/.
  - make DESTDIR=/home/travis/build/GuillaumeGomez/rust-music-player/sfml_install install
  - cd ../..

script:
  - rustc --version
  - cargo build

addons:
  apt:
    packages:
    - libpthread-stubs0-dev
    - libgl1-mesa-dev
    - libx11-dev
    - libx11-xcb-dev
    - libxcb-image0-dev
    - libxrandr-dev
    - libxcb-randr0-dev
    - libudev-dev
    - libfreetype6-dev
    - libglew-dev
    - libjpeg8-dev
    - libgpgme11-dev
    - libsndfile1-dev
    - libopenal-dev
    - libjpeg62
    - 